//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_4._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int ID_Product { get; set; }
        public string ProductName { get; set; }
        public decimal PriceProduct { get; set; }
    }
}
